# Generated by Django 3.2.5 on 2021-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_stocks_sellingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
